#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"
if which yarn >/dev/null; then
    pack=yarn
elif which pnpm >/dev/null; then
    pack=pnpm
else
    pack=npm
fi

node "$(dirname -- "$0")/tester.js" -f pre-commit